---
# tasks file for tomcat_setup_check
- name: check if java exists or not
  stat:
    path: /usr/lib/jvm/java
  register: java_installed

- name: "java is installed "
  debug:
     msg: "java is exists"
  when: java_installed.stat.exists == True

- name: "java is not installed"
  debug:
    msg: "java doesn't exists"
  when: java_installed.stat.exists == False

- name: install java
  yum:
    name: java
    state: installed   
  when: java_installed.stat.exists == False

- name: check if apache-tomcat exists or not
  stat:
    path: /opt/apache-tomcat-8.5.83 
  register: apache_tomcat_installed

- name: "Tomcat is installed and starting tomcat services" 
  debug:
     msg: "apache-tomcat-8.5.83 is exists"
  notify: start tomcat services
  when: apache_tomcat_installed.stat.exists == True
  


- name: "Tomcat is not installed"
  debug:
    msg: "apache-tomcat-8.5.83 doesn't exists"
  when: apache_tomcat_installed.stat.exists == False

- name: downloading tomcat packages
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt
    mode: 0755
  when: apache_tomcat_installed.stat.exists == False

- name: extract packages
  unarchive:
    src: /opt/{{ tomcat_package }}.tar.gz
    dest: /opt
    remote_src: yes
  when: apache_tomcat_installed.stat.exists == False

- name: change permissions on apache-tomcat file
  file:
    path: /opt/{{ tomcat_package }}
    mode: 0755
    recurse: yes
  when: apache_tomcat_installed.stat.exists == False

- name: creating link file
  file:
    src: /opt/{{ tomcat_package }}/bin/{{ item.tomcat_script }}
    dest: /usr/local/bin/{{ item.tomcat_cmd }}
    state: link
  loop:
        - { tomcat_script: 'startup.sh' , tomcat_cmd: tomcatup}
        - { tomcat_script: 'shutdown.sh' , tomcat_cmd: tomcatdown}        
  notify: start tomcat services
  when: apache_tomcat_installed.stat.exists == False


- name: Adding Tomcat users
  copy:
    src: server.xml
    dest: /opt/{{ tomcat_package }}/conf/server.xml
  notify: restart tomcat services
  when: apache_tomcat_installed.stat.exists == False

